openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: RESTful API for managing user tasks with authentication and data isolation
  contact:
    name: Todo App Team
    email: dev@todoapp.example

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  # Task CRUD Endpoints
  /api/{user_id}/tasks:
    get:
      summary: List all tasks for a user
      operationId: listTasks
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: User ID from JWT token
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [Pending, Completed, All]
            description: Filter tasks by status
      responses:
        '200':
          description: List of tasks retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - invalid or missing JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - user_id in URL does not match JWT user_id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a new task
      operationId: createTask
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Validation error - invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/{user_id}/tasks/{task_id}:
    get:
      summary: Get a specific task
      operationId: getTask
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - task does not belong to user
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a task
      operationId: updateTask
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Task not found
        '422':
          description: Validation error

    delete:
      summary: Delete a task
      operationId: deleteTask
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Task not found

  /api/{user_id}/tasks/{task_id}/complete:
    patch:
      summary: Mark task as completed
      operationId: completeTask
      security:
        - BearerAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task marked as completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Task not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Better Auth

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - status
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique task identifier
        user_id:
          type: string
          format: uuid
          description: Owner user ID
        title:
          type: string
          maxLength: 500
          description: Task title
        description:
          type: string
          description: Detailed task information
        status:
          type: string
          enum: [Pending, Completed]
          description: Current task state
        created_at:
          type: string
          format: date-time
          description: When task was created
        completed_at:
          type: string
          format: date-time
          nullable: true
          description: When task was completed
        updated_at:
          type: string
          format: date-time
          description: Last modification time

    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 500
          description: Task title (required)
        description:
          type: string
          description: Task description (optional)

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 500
          description: Task title (optional)
        description:
          type: string
          description: Task description (optional)
        status:
          type: string
          enum: [Pending, Completed]
          description: Task status (optional)

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Human-readable error message
        detail:
          type: string
          description: Additional error details
